# Numpy

In [ ]:
import numpy as np
arr=np.array([1,0,1,0])
print(arr)


In [5]:
import numpy as np
arr=np.array([(1,0,1,0),(1,1,1,6)])
print(arr)


[[1 0 1 0]
 [1 1 1 6]]


In [9]:
a=np.arange(10)
d=np.linspace(1,5,6)  #divide into equal parts
print(a)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[1.  1.8 2.6 3.4 4.2 5. ]


# Properties of numpy

In [38]:
print(a.ndim) #dimensional
print(a.itemsize) #byte size of each element
print(a.dtype) #datatype of array
print(a.size*a.itemsize) #memory occupied of whole array
print(a.size)
print(a.shape)

1
4
int32
40
10
(10,)


# two dimensional

In [66]:
b=np.array([(1,1,1),(2,2,2)])
print(b)
b=b.reshape(3,2)
print(b)
print(b[1][0])  #both ways we can access
print(b[1,0])

[[1 1 1]
 [2 2 2]]
[[1 1]
 [1 2]
 [2 2]]
1
1


In [36]:
b=np.array([(7,9,9,2),(2,1,3,2)])
print(b[0,2])
print(b[0:,2]) 

9
[9 3]


In [54]:
print(b.min())
print(b.max())
print(b.sum(axis=0)) # sum column wise 
print(b.sum(axis=1))  #sum row 
print(np.sqrt(b)) # square root of array 
print(np.std(b)) # standard deviation
print(np.exp(b))  # exponent
print(np.log(b))
print(np.log10(a))

1
9
[ 9 10 12  4]
[27  8]
[[2.64575131 3.         3.         1.41421356]
 [1.41421356 1.         1.73205081 1.41421356]]
3.1598061649411346
[[1.09663316e+03 8.10308393e+03 8.10308393e+03 7.38905610e+00]
 [7.38905610e+00 2.71828183e+00 2.00855369e+01 7.38905610e+00]]
[[1.94591015 2.19722458 2.19722458 0.69314718]
 [0.69314718 0.         1.09861229 0.69314718]]
[      -inf 0.         0.30103    0.47712125 0.60205999 0.69897
 0.77815125 0.84509804 0.90308999 0.95424251]


C:\Users\shrin\AppData\Local\Temp\ipykernel_8676\2402248254.py:9: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(a))


In [60]:
b=np.array([(7,9,9,1),(1,2,3,4)])
f=np.array([(4,3,2,1),(4,5,6,7)])
print(np.vstack((b,f))) #vertical stack
print(np.hstack((b,f))) #horizontal stack 
print(b.ravel()) #merge into single dimensional array

[[7 9 9 1]
 [1 2 3 4]
 [4 3 2 1]
 [4 5 6 7]]
[[7 9 9 1 4 3 2 1]
 [1 2 3 4 4 5 6 7]]
[7 9 9 1 1 2 3 4]


# Three  dimensional array

In [63]:
three=np.array([
    [[1,2,3],[4,5,6]],
    [[3,2,3],[4,5,6]],
])
print(three)
print(three.ndim)

[[[1 2 3]
  [4 5 6]]

 [[3 2 3]
  [4 5 6]]]
3


## shape of all dimensions

In [69]:
print(a.shape)
print(b.shape)
print(three.shape)

(10,)
(3, 2)
(2, 2, 3)


## size

In [72]:
print(a.size)
print(b.size)
print(three.size)

10
6
12


In [80]:
for i in b:
    for j in i:
        print(j)

1
1
1
2
2
2


In [76]:
for i in three.ravel(): 
    print(i)

1
2
3
4
5
6
3
2
3
4
5
6


In [74]:
for i in three.flatten(): #convert to any dimensional to single dimensional
    print(i)

1
2
3
4
5
6
3
2
3
4
5
6


## filling arrays with specific values

In [83]:
#zeros

In [85]:
zeros=np.zeros(5)  #return float 
print(zeros)

[0. 0. 0. 0. 0.]


In [89]:
#ones
ones=np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [93]:
#convert one datatype to another
ones=ones.astype(int)    #return new copy of array 
print(ones)

[1 1 1 1 1]


In [99]:
ranges=np.arange(5.6,9.8) #difference between range and aramge is arange support decimal values
print(ranges)

[5.6 6.6 7.6 8.6 9.6]


In [103]:
ad=np.array([1,2,3,4])
print(ad+2) #adds 2 to each element

[3 4 5 6]


In [107]:
print(b.T) #transpose (convert row to column)

[[1 1 2]
 [1 2 2]]


In [119]:
print("Adding default values")
print(np.full(10,5))
print(np.full((2,2),10))
print(np.full((2,2,2),10))

Adding default values
[5 5 5 5 5 5 5 5 5 5]
[[10 10]
 [10 10]]
[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]


In [123]:
list1=[[10,10],[2,1]]
list2=[[10,10],[2,1]]
print(list1+list2)   #concat it will return new list by concatanating elements

[[10, 10], [2, 1], [10, 10], [2, 1]]


In [129]:
m1=np.array([[7,9],[1,2]])
m2=np.array([[4,3],[4,5]])
print(m1+m2)
print(m1-m2)
print(np.matmul(m1,m2))

[[11 12]
 [ 5  7]]
[[ 3  6]
 [-3 -3]]
[[64 66]
 [12 13]]


# statitics

In [144]:
marks=np.array([[20,30,40],[1,2,3],[11,2,7],[3,33,44]])
print(marks.min())
print(marks.max())
print(marks.sum())
print(marks.mean())
print(marks.std())


1
44
196


### axis 1 = row wise

In [149]:
print(marks.min(axis=1))
print(marks.max(axis=1))
print(marks.sum(axis=1))
print(marks.mean(axis=1))
print(marks.std(axis=1))


[20  1  2  3]
[40  3 11 44]
[90  6 20 80]
[30.          2.          6.66666667 26.66666667]
[ 8.16496581  0.81649658  3.68178701 17.32692189]


In [151]:
print(marks.min(axis=0))
print(marks.max(axis=0))
print(marks.sum(axis=0))
print(marks.mean(axis=0))
print(marks.std(axis=0))


[1 2 3]
[20 33 44]
[35 67 94]
[ 8.75 16.75 23.5 ]
[ 7.49583218 14.78808642 18.60779407]


In [163]:
arr1=np.array([[20,30,40],[1,2,3],[11,2,7],[3,33,44]])
arr2=np.append(arr1,(5,6,7)) #it will take existing array and add new values and return new array of single dimnesion
print(arr2.ndim)

1


In [173]:
new_array=np.array([1,2])
x=np.append([[2,3],[45,6]],[[30,40],new_array],axis=1)
x

array([[ 2,  3, 30, 40],
       [45,  6,  1,  2]])

In [181]:
arr3=np.arange(7)
print(arr3)
print(arr3>4)
print(arr3[arr3>4])

[0 1 2 3 4 5 6]
[False False False False False  True  True]
[5 6]


In [183]:
np.random.randint(10,20,(5,5)) #5*5 matrix with values from 10 to 20 randomly

array([[19, 10, 16, 12, 14],
       [17, 17, 12, 14, 14],
       [16, 10, 13, 18, 16],
       [10, 13, 18, 14, 12],
       [13, 19, 14, 12, 14]])

In [187]:
letters=['a','e','o','u','i']
np.random.choice(letters,5) #return many occurances of one letter

array(['o', 'o', 'e', 'o', 'a'], dtype='<U1')

In [189]:
np.random.choice(letters,5,replace=False) #it will not return many occurances of one letter

array(['o', 'i', 'e', 'u', 'a'], dtype='<U1')

In [197]:
np.random.choice(letters,15,p=[0.4,0.1,0.1,0.3,0.1]) #probabilty for each letter  it should sum up to 1

array(['o', 'a', 'e', 'a', 'a', 'u', 'u', 'a', 'a', 'a', 'i', 'u', 'e',
       'a', 'o'], dtype='<U1')

In [199]:
array=np.random.randint(10,20,(5,5))
np.save('array_file',array) #default extension is .npy

In [203]:
array2=np.load('array_file.npy')
print(array2)

[[15 18 13 16 15]
 [19 16 16 13 16]
 [16 13 13 18 17]
 [11 16 17 17 12]
 [17 13 10 10 17]]
